# Generated by Django 6.1.1 on 2026-09-15 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='courses.course')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
                'indexes': [models.Index(fields=['course', 'is_active'], name='courses_bat_course__2dd092_idx')],
                'constraints': [models.UniqueConstraint(fields=('course', 'name'), name='uniq_batch_name_per_course')],
            },
        ),
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_skills', to='courses.course')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_skills', to='skills.skill')),
                ('sub_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_skills', to='skills.subskill')),
            ],
            options={
                'ordering': ['course', 'skill', 'sub_skill'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('sub_skill__isnull', False)), fields=('course', 'skill', 'sub_skill'), name='uniq_course_skill_subskill'), models.UniqueConstraint(condition=models.Q(('sub_skill__isnull', True)), fields=('course', 'skill'), name='uniq_course_skill_without_subskill')],
            },
        ),
    ]
