# Generated by Django 6.1.1 on 2026-09-15 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_initial'),
        ('courses', '0001_initial'),
        ('performance', '0001_initial'),
        ('skills', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='overallperformance',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overall_performances', to='courses.batch'),
        ),
        migrations.AddField(
            model_name='overallperformance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overall_performances', to='courses.course'),
        ),
        migrations.AddField(
            model_name='overallperformance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_performances', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='overall_performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='performance.overallperformance'),
        ),
        migrations.AddField(
            model_name='skillevidence',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evidences', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='skillevidence',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evidences', to='activities.evaluation'),
        ),
        migrations.AddField(
            model_name='skillevidence',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='skillevidence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evidences', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='skillevidence',
            name='sub_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='skills.subskill'),
        ),
        migrations.AddField(
            model_name='skillscore',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_scores', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='skillscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_scores', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='subskillscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_skill_scores', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='subskillscore',
            name='sub_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_scores', to='skills.subskill'),
        ),
        migrations.AddIndex(
            model_name='overallperformance',
            index=models.Index(fields=['course', 'batch'], name='performance_course__9d0b60_idx'),
        ),
        migrations.AddConstraint(
            model_name='overallperformance',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'batch'), name='uniq_overall_performance_per_student_context'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['ranking_scope', 'rank'], name='performance_ranking_4046ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaderboardentry',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', True), ('course__isnull', True)), fields=('student', 'ranking_scope'), name='uniq_leaderboard_global_entry'),
        ),
        migrations.AddConstraint(
            model_name='leaderboardentry',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', True), ('course__isnull', False)), fields=('student', 'ranking_scope', 'course'), name='uniq_leaderboard_course_entry'),
        ),
        migrations.AddConstraint(
            model_name='leaderboardentry',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', False), ('course__isnull', False)), fields=('student', 'ranking_scope', 'course', 'batch'), name='uniq_leaderboard_batch_entry'),
        ),
        migrations.AddIndex(
            model_name='skillevidence',
            index=models.Index(fields=['student', 'sub_skill'], name='performance_student_4d7795_idx'),
        ),
        migrations.AddIndex(
            model_name='skillevidence',
            index=models.Index(fields=['evaluation'], name='performance_evaluat_119b6e_idx'),
        ),
        migrations.AddIndex(
            model_name='skillevidence',
            index=models.Index(fields=['is_valid'], name='performance_is_vali_8fc43e_idx'),
        ),
        migrations.AddConstraint(
            model_name='skillevidence',
            constraint=models.UniqueConstraint(fields=('evaluation', 'sub_skill'), name='uniq_evidence_per_evaluation_subskill'),
        ),
        migrations.AddIndex(
            model_name='skillscore',
            index=models.Index(fields=['proficiency_level'], name='performance_profici_906e02_idx'),
        ),
        migrations.AddConstraint(
            model_name='skillscore',
            constraint=models.UniqueConstraint(fields=('student', 'skill'), name='uniq_skill_score_per_student'),
        ),
        migrations.AddConstraint(
            model_name='subskillscore',
            constraint=models.UniqueConstraint(fields=('student', 'sub_skill'), name='uniq_subskill_score_per_student'),
        ),
    ]
