# Generated by Django 6.1.1 on 2026-09-15 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('CURRENT', 'Current'), ('SUPERSEDED', 'Superseded')], default='CURRENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-overall_score', 'student'],
            },
        ),
        migrations.CreateModel(
            name='SkillEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField()),
                ('is_valid', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'skill evidences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('proficiency_level', models.CharField(choices=[('FOUNDATIONAL', 'Foundational'), ('DEVELOPING', 'Developing'), ('PROFICIENT', 'Proficient'), ('ADVANCED', 'Advanced')], default='FOUNDATIONAL', max_length=20)),
                ('status', models.CharField(choices=[('CURRENT', 'Current'), ('SUPERSEDED', 'Superseded')], default='CURRENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['student', 'skill'],
            },
        ),
        migrations.CreateModel(
            name='SubSkillScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('CURRENT', 'Current'), ('SUPERSEDED', 'Superseded')], default='CURRENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['student', 'sub_skill'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_scope', models.CharField(choices=[('GLOBAL', 'Global'), ('COURSE', 'Course'), ('BATCH', 'Batch')], max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leaderboard_entries', to='courses.batch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leaderboard_entries', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'leaderboard entries',
                'ordering': ['ranking_scope', 'rank'],
            },
        ),
    ]
