# Generated by Django 6.1.1 on 2026-09-15 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('skills', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluationhistory',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='activities.evaluation'),
        ),
        migrations.AddField(
            model_name='evaluationhistory',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_history_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_mappings', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='projectskill',
            name='sub_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_mappings', to='skills.subskill'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='activities.assessmentsection'),
        ),
        migrations.AddField(
            model_name='question',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='question',
            name='sub_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='skills.subskill'),
        ),
        migrations.AddField(
            model_name='submission',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='activities.submission'),
        ),
        migrations.AddField(
            model_name='taskskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_mappings', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='taskskill',
            name='sub_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_mappings', to='skills.subskill'),
        ),
        migrations.AddField(
            model_name='assessmentsection',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='activities.assessment'),
        ),
        migrations.AddField(
            model_name='projectskill',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_mappings', to='activities.project'),
        ),
        migrations.AddField(
            model_name='taskskill',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_mappings', to='activities.task'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type', 'status'], name='activities__activit_5ac397_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['course', 'batch'], name='activities__course__e18cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['skill', 'sub_skill'], name='activities__skill_i_3e05fa_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'activity'], name='activities__student_93903f_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='activities__status_ac8138_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['status'], name='activities__status_5003a7_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['evaluator'], name='activities__evaluat_601763_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsection',
            constraint=models.UniqueConstraint(fields=('assessment', 'title'), name='uniq_section_title_per_assessment'),
        ),
        migrations.AddConstraint(
            model_name='projectskill',
            constraint=models.UniqueConstraint(condition=models.Q(('sub_skill__isnull', False)), fields=('project', 'skill', 'sub_skill'), name='uniq_project_skill_subskill'),
        ),
        migrations.AddConstraint(
            model_name='projectskill',
            constraint=models.UniqueConstraint(condition=models.Q(('sub_skill__isnull', True)), fields=('project', 'skill'), name='uniq_project_skill_without_subskill'),
        ),
        migrations.AddConstraint(
            model_name='taskskill',
            constraint=models.UniqueConstraint(condition=models.Q(('sub_skill__isnull', False)), fields=('task', 'skill', 'sub_skill'), name='uniq_task_skill_subskill'),
        ),
        migrations.AddConstraint(
            model_name='taskskill',
            constraint=models.UniqueConstraint(condition=models.Q(('sub_skill__isnull', True)), fields=('task', 'skill'), name='uniq_task_skill_without_subskill'),
        ),
    ]
