# Generated by Django 6.1.1 on 2026-09-24 11:38

from django.db import migrations, models


def populate_display_order(apps, schema_editor):
    SubSkill = apps.get_model('skills', 'SubSkill')
    Skill = apps.get_model('skills', 'Skill')
    for skill in Skill.objects.all():
        subskills = SubSkill.objects.filter(skill=skill).order_by('created_at', 'id')
        for order, sub in enumerate(subskills, start=1):
            sub.display_order = order
            sub.save(update_fields=['display_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subskill',
            options={'ordering': ['skill', 'display_order', 'id']},
        ),
        migrations.AddField(
            model_name='subskill',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(populate_display_order, migrations.RunPython.noop),
    ]

